spring:
  config:
    import: aws-parameterstore:/camp-health-app/prod/

  cloud:
    aws:
      region:
        static: ap-northeast-2

  datasource:
    url: jdbc:mysql://my-database.c3yam22is5sf.ap-northeast-2.rds.amazonaws.com:3306/test
    username: admin
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

info:
  team-name: ${team-name}