spring:
  application:
    name: CloudProject

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true

cloud:
  aws:
    s3:
      bucket: team-mbti-homework-devdong1231
      region: ap-northeast-2