@baseUrl = 52.78.204.238

### 멤버 생성
POST http://{{baseUrl}}:8080/api/members
Content-Type: application/json

{
  "name": "김유하",
  "age": 23,
  "mbti": "ISTJ"
}

### 멤버 생성 오류1
POST http://{{baseUrl}}:8080/api/members
Content-Type: application/json

{
"name": "김유하",
"age": 23
}

### 멤버 생성 오류2
POST http://{{baseUrl}}:8080/api/members
Content-Type: application/json

{
  "name": "김유하",
  "age": 23,
  "mbti": ""
}

### 멤버 생성 오류3
POST http://localhost:8080/api/members
Content-Type: application/json

{
  "name": "김유하",
  "age": 23,
  "mbti": "ISTSDFJ"
}